name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDJlZDNhYzgtYzNiNi00MzQzLTgzZjgtYWZmOGI1NTM1ZDY3IiwidGVuYW50X2lkIjoiZDQ2MDg5ODU5ZjAyM2VmZDdhN2ViMTdlZmM5NDY4Y2EyMGUwODhiYmE5MDE4YzlmNGVjNWQ3ZjcxNWZmNTFiNiIsImludGVybmFsX3NlY3JldCI6Ijc4NmRlYzYyLWExNmUtNGM0Yi04YTg3LTcwNzc0ZjUzMDc4OCJ9.UdYBAh4Q2QktwWkdG29JgEN-FMLxscpWv4FTLOf0Y-8"
JWT_SECRET = 'saurabhiscool'

